### ISSUE TITLE
Feed me!

### ISSUE THREAD

**Issue by karamassie** [karamassie/zucchini#2]
- [ ] not the kind that was approved yesterday
- [ ] what's this dehydrated brown niblet?! Am I an astronaut? wet, only.
- [ ] notification set for 15mins or when user is sleeping
